// Code generated by g v (b); DO NOT EDIT



// Events:
// 

// Model handles the business logic by using generated functions.
class Model extends FlatElement {
    // constructor ...
    constructor() {
        super();
		// add event listeners
		
    }
}

// ViewModel handles the state and provides a simple API.
class ViewModel extends FlatElement {
    // constructor ...
    constructor() {
        super();
        // add event listeners
		
	}
	
}

const model = new Model();
const viewModel = new ViewModel();
