package templates

// MakeBat ...
var MakeBat = `REM Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT
@echo off
cls
setlocal EnableDelayedExpansion

echo getting info from Git ...
git pull
git rev-parse --short HEAD > build.txt
SET /p BUILD=<build.txt
echo BUILD   = %BUILD%
git describe --tags > version.txt
SET /p VERSION=<version.txt
echo VERSION = %VERSION%
echo.

echo start building ...
go mod tidy
go mod vendor
go generate ./...
echo go build --ldflags '-s -w -X=main.build=%BUILD% -X=main.name={{ .Name }} -X=main.version=%VERSION%' -o {{ .Name }}.exe main.go 
echo done.

.\{{ .Name }}.exe
`
