package templates

// PasswordTestGo ...
var PasswordTestGo = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

package secure_test

import (
	"testing"

	"{{ .Path }}/pkg/assert"
	"{{ .Path }}/pkg/secure"
)

func TestCreatePasswordHash(t *testing.T) {
	password := []byte("asdf 1234")
	hash := secure.HashPassword(password)
	assert.That("Password Hash should be valid", t, secure.IsPasswordHashValid(password, hash), true)
}
`
