package templates

// PasswordGo ...
var PasswordGo = `// Code generated by create-go-app v0.0.90 (b4a9599); DO NOT EDIT

package secure

import (
	"golang.org/x/crypto/bcrypt"
)

// HashPassword ...
func HashPassword(password []byte) (hash []byte) {
	hash, _ = bcrypt.GenerateFromPassword(password, 14)
	return
}

// IsPasswordHashValid ...
func IsPasswordHashValid(password, hash []byte) (ok bool) {
	return bcrypt.CompareHashAndPassword(hash, password) == nil
}
`
