package templates

// RoutesGo ...
var RoutesGo = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

package server

import (
	"net/http"
	"os"
	"path/filepath"
)

func (s *Server) routes() {
	path, _ := os.Getwd()
	staticPath := filepath.Join(path, "web", "static")
	s.router.HandleFunc("/metrics", s.withLogging(s.handleMetrics()))
	s.router.HandleFunc("/status", s.withLogging(s.withMetrics(s.handleStatus())))
	s.router.Handle("/", http.FileServer(http.Dir(staticPath)))
}`
