package templates

// ServiceWorker ...
var ServiceWorker = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

var CACHE_NAME = "{{ .Name }}_{{ .Version }}";

var cachedFiles = [
	"/",
	"/bundle.css",
	"/bundle.js"
];

self.addEventListener("install", (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME)
		.then((cache) => {
			console.log("ServiceWorker cache " + CACHE_NAME + " installed.");
			return cache.addAll(cachedFiles);
		})
	);
});

`
