package templates

// ServiceWorker ...
var ServiceWorker = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

var CACHE_NAME = "{{ .Name }}_{{ .Version }}";

var cachedFiles = [
	"/",
	"/bundle.css",
	"/bundle.js"
];

self.addEventListener("install", (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME)
		.then((cache) => {
			console.log("ServiceWorker cache " + CACHE_NAME + " installed.");
			return cache.addAll(cachedFiles);
		})
	);
});

self.addEventListener("fetch", (event) => {
	event.respondWith(
		fetch(event.request)
		.then((response) => {
			console.log("ServiceWorker resource " + event.request.url + " fetched from backend.");
			return response;
		})
		.catch((err) => {
			console.log("ServiceWorker resource " + event.request.url + " fetched from cache.");
			return new Response(fallbackData["status"], { "headers": { "content-type": "application/json" }});
		})
	)
});
`
