package templates

// APIClient ...
var APIClient = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT
{{ $app := .Name }}
// Events:
// {{ range $i, $name := .Services }} 
// {{ $i }}: "{{ sc $name }}" will be the Event which triggers the Command.
//    "{{ sc $name }} done" will be Event which has the Result.
//    "{{ sc $name }} result" will be Key for accessing the Data.
// {{ end }}

// Model handles the business logic by using generated functions.
class Model extends FlatElement {
    // constructor ...
    constructor() {
        super();
		// add event listeners
		{{ range $i, $name := .Services }}
        this.on("{{ sc $name }}", async (params) => {
			let config = {
				method: "POST",
				headers: {
					"accept": "application/json",
					"content-type": "application/json"
				},
				body: JSON.stringify(params)
			};
			let response = await fetch("/{{ sc $name }}", config);
			let data = await response.json();
            this.emit("{{ sc $name }} done", data);
		});
		{{ end }}
    }
}

// ViewModel handles the state and provides a simple API.
class ViewModel extends FlatElement {
    // constructor ...
    constructor() {
        super();
        // add event listeners
		{{ range $i, $name := .Services }}
        this.on("{{ sc $name }} done", (data) => {
             this.setState("{{ sc $name }} result", data);
		});
		{{ end }}
	}
	{{ range $i, $name := .Services }}
    {{ sc $name }}(data) {
        this.emit("{{ sc $name }}", data);
	}
	{{ end }}
}

const model = new Model();
const viewModel = new ViewModel();
`
