package templates

var Dockerfile = `# Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

FROM golang:1.15.2-alpine3.12

WORKDIR /go/src/app
COPY . .

ENV CGO_ENABLED 0

RUN go build -ldflags "-s -w -X=main.build={{ .Build }} -X=main.name={{ .Name }} -X=main.version={{ .Version }}" -o /app main.go

CMD ["/app"]
`
