package templates

// Makefile ...
var Makefile = `# Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

BUILD := $(shell git rev-parse --short HEAD)
MODULE := $(shell cut -f2 -d" " go.mod | head -1)
NAME := $(shell basename "$(PWD)")
VERSION := $(shell git describe --tags)

BIN := $(GOPATH)/bin/$(NAME)
LDFLAGS=-ldflags "-s -w -X=main.build=$(BUILD) -X=main.name=$(NAME) -X=main.version=$(VERSION)"

all : generate compile run

build-image :
	@docker build -t $(NAME):$(VERSION) -f build/Dockerfile .
	@docker tag $(NAME):$(VERSION) $(NAME):latest

compile :
	@go mod tidy
	@go mod vendor
	@go build $(LDFLAGS) -o $(BIN) main.go

generate :
	@go generate ./...

licenses :
	@go-licenses csv $(MODULE) > LICENSE.csv

run :
	$(BIN)

run-container :
	@docker rm -f $(NAME) ; /bin/true
	@docker run -p 3000:3000 -dit --name $(NAME) $(NAME):$(VERSION)
`
