package templates

var MakeBat = `REM Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT
@echo off
cls
setlocal EnableDelayedExpansion

echo start building ...
go mod tidy
go mod vendor
go generate ./...
go build --ldflags "-s -w" -X=main.build={{ .GitBuild }} -X=main.name={{ .Name }} -X=main.version={{ .GitVersion }}" -o {{ .Name }}.exe main.go
echo done.

.\{{ .Name }}.exe
`
