package templates

// MiddlewareGo ...
var MiddlewareGo = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

package server

import (
	"net/http"
	"time"
)

func (s *Server) withMetrics(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		s.metrics.mutex.Lock()
		s.metrics.RequestCount[r.RequestURI]++
		s.metrics.mutex.Unlock()
		start := time.Now()
		next.ServeHTTP(w, r)
		s.metrics.mutex.Lock()
		s.metrics.ResponseTimeMs[r.RequestURI] = int(time.Since(start).Milliseconds())
		s.metrics.mutex.Unlock()
	}
}

func (s *Server) withLogging(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		s.logger.Printf("%-6s %-20s %-50s", "INFO", r.RemoteAddr, r.RequestURI)
		next.ServeHTTP(w, r)
	}
}`
