package templates

// RepositoryUtilGo ...
var RepositoryUtilGo = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

package repository

import (
	"encoding/json"
	"io/ioutil"
)

// DecodeFile ...
func DecodeFile(path string) (data map[string]interface{}, err error) {
	bytes, err := ioutil.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(bytes, &data); err != nil {
		return nil, err
	}
	return
}

// EncodeFile ...
func EncodeFile(path string, data map[string]interface{}) error {
	bytes, err := json.Marshal(data)
	if err != nil {
		return err
	}
	return ioutil.WriteFile(path, bytes, 0644)
}
`
