package templates

// Routes2Go ...
var Routes2Go = `// Code generated by {{ .Generator }} {{ .Version }} ({{ .Build }}); DO NOT EDIT

package server

import (
	"net/http"
	"os"
	"path/filepath"
)

func (s *Server) routes() {
	path, _ := os.Getwd()
	staticPath := filepath.Join(path, "web", "static")
	s.router.HandleFunc("/metrics", s.withLogging(s.handleMetrics()))
	{{ range $i, $name := .Services }}s.router.HandleFunc("/{{ sc $name }}", s.withLogging(s.withMetrics(s.handle{{ $name }}())))
	{{ end }}s.router.Handle("/", http.FileServer(http.Dir(staticPath)))
}`
